### ISSUE TITLE
Code breaks with non inteager inputs

### ISSUE THREAD

**Issue by ghost** [madhvendra13/devops-prj#1]
![7d01bea1-bcd1-4cfd-957f-71cdf23d87c9](https://github.com/madhvendra13/devops-prj/assets/143247808/7897f5bd-4423-4322-a48f-d283e39c3cb3)

**Comment by madhvendra13** [comment]
thank you for the suggestion . Looking into it

**Comment by ghost** [comment]
@madhvendra13 Can I work on this issue?

**Comment by ghost** [comment]
Error is fixed in [#7b91fd5d8](https://github.com/madhvendra13/devops-prj/commit/7b91fd5d8eb76af20d9484bcdd9b1bace39fb35a)

Closing the issue
